// Woohoo okay here's a bunch of data

export const allLocData = [
  // Just an example
  {
    id: 'seattle-usa',
    location: { city: 'Seattle', country: 'United States' },
    ambientMessages: [
      'The sound of seagulls fills the air.',
      'Raindrops patter softly on the pavement.',
      'A distant hum of traffic echoes through the city.',
      'Locals stroll by, clutching coffee cups.',
      'A street musician plays a melodic tune on a guitar.',
      'The scent of freshly baked pastries wafts from a nearby bakery.',
      'Faint sounds of a ferry horn can be heard from the waterfront.',
      'Pedestrians navigate the city with colorful rain jackets.',
      'The Space Needle stands tall against the gray sky.',
      'A coffee shop offers a cozy refuge from the drizzle outside.',
      'Cyclists pedal along the streets, raindrops glistening on their jackets.',
      "A bookshop's door chimes as customers seek shelter from the rain.",
      'A jogger passes by, undeterred by the light drizzle.',
      'The Pike Place Market bustles with activity, even in the rain.',
      'A faint smell of saltwater drifts in from the Puget Sound.',
      'Seattlites converse in a local cafe, the atmosphere warm and inviting.',
      'A street vendor sells hot soup to passersby.',
      'The monorail glides above, connecting different parts of the city.',
      "An art gallery's windows showcase vibrant paintings against the gray backdrop.",
      'Commuters huddle at bus stops, checking their phones while waiting.',
    ],
  },
  {
    id: 'tokyo-japan',
    location: { city: 'Tokyo', country: 'Japan' },
    ambientMessages: [
      'The bustling streets are filled with the harmonious blend of pedestrian chatter and distant traffic.',
      'Neon lights illuminate the night, turning the cityscape into a vibrant display of colors.',
      'The aroma of street food wafts through the air, tempting passersby with delicious treats.',
      'A gentle breeze carries cherry blossom petals, creating a picturesque scene in the spring.',
      'Cyclists navigate through the crowded streets, skillfully weaving between pedestrians.',
      'A street performer captivates a small audience with a mesmerizing traditional performance.',
      'The hum of the subway resonates as trains arrive and depart with clockwork precision.',
      'Locals and tourists alike explore the diverse range of shops in the bustling districts.',
      'Rain falls softly, creating a reflective shimmer on the city streets.',
      'A tranquil garden provides a peaceful retreat from the urban hustle and bustle.',
      'The iconic Tokyo Tower stands tall, a symbol of the city against the backdrop of the skyline.',
      'A sushi chef expertly prepares fresh fish behind the counter of a traditional sushiya.',
      "Harajuku's fashionable youth showcase unique styles, turning the streets into a fashion runway.",
      'In the quiet corners of temples, the soft sounds of rituals create a serene atmosphere.',
      'Businessmen and women hurry along, briefcases in hand, navigating the corporate heart of the city.',
      'A capsule hotel hums with activity as travelers check in and out, embracing the futuristic accommodation.',
      'The electronic beats of a video game arcade spill onto the street, inviting players inside.',
      "Shinto shrines offer a glimpse into Japan's rich cultural and spiritual heritage.",
      "The efficient and punctual metro system is a lifeline, connecting Tokyo's diverse neighborhoods.",
      'A tea ceremony unfolds in a traditional tearoom, emphasizing precision and mindfulness.',
    ],
  },
  {
    id: 'new-york-usa',
    location: { city: 'New York', country: 'United States' },
    ambientMessages: [
      'The city that never sleeps lives up to its name as the streets buzz with activity at all hours.',
      'Skyscrapers reach towards the sky, creating a breathtaking urban canyon of glass and steel.',
      "The aroma of street vendors' pretzels and hot dogs mingles with the scent of coffee from nearby cafes.",
      'Yellow taxis weave through traffic, a constant presence in the ebb and flow of city life.',
      'Street performers entertain crowds with music, magic, and artistic performances.',
      'The distinctive honking of car horns becomes a rhythmic backdrop to the urban symphony.',
      'Central Park offers a green oasis in the midst of the bustling metropolis.',
      'Subway cars rumble below ground, transporting millions of people throughout the expansive city.',
      'The lights of Times Square create a kaleidoscope of colors, illuminating the heart of Manhattan.',
      "Diverse languages and accents blend in a cacophony of voices, reflecting the city's cultural tapestry.",
      'Artists sketch the iconic skyline along the waterfront, capturing the essence of the city on canvas.',
      'Food trucks line the streets, offering a culinary journey through different cuisines.',
      "Pedestrians rush across busy intersections, each person a character in the city's dynamic narrative.",
      'The reflection of city lights dances on the surface of the Hudson River at night.',
      "Historic brownstones stand as a testament to the city's architectural heritage.",
      'The hushed tones of conversations in the New York Public Library create an atmosphere of intellectual pursuit.',
      'Fire escapes adorn brick buildings, creating an iconic feature of the cityscape.',
      'Fashion-forward New Yorkers stride confidently, showcasing a spectrum of styles and trends.',
      'Broadway marquees light up the Theater District, promising a night of entertainment and wonder.',
      'The skyline transforms into a glittering panorama as night falls on the city that captivates hearts worldwide.',
    ],
  },
];
